import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ConvexClientProvider } from "~/Providers/Convex";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
// import { ThemeProvider } from "~/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" className={`${geist.variable}`}>
        <body>
          {/* <ThemeProvider defaultTheme="light" storageKey="t3-chat-theme"> */}
          <ConvexClientProvider>{children}</ConvexClientProvider>
          {/* </ThemeProvider> */}
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
